version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/docs"
      - "/packages/*"
      - "/packages/create-starknet/src/templates/next"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    groups:
      github-actions:
        patterns:
          - "*"
